### ISSUE TITLE
fips mode not supported by openssl on alpine 3.6

### ISSUE THREAD

**Issue by spk83** [andrewrothstein/ansible-stunnel-config#1]
To make it work with fips=yes, alpine image has to be created like this - https://github.com/NineFX/alpine-fips 🤕

**Comment by andrewrothstein** [comment]
how about we drops fips=yes support? or drop alpine support? been looking at [envoy](https://github.com/lyft/envoy) and [istio](https://github.com/istio/istio). maybe use them instead and get so much more?

**Comment by spk83** [comment]
istio looks promising! will try it out, thanks! existing k8s-cluster role needs a bit love before I can run this.
I dropped fips=yes support for now to run on alpine.
